import pandas as pd
from typing import TypedDict, Annotated
import operator
from profile import UserProfile
from huggingface_hub import InferenceClient
from langgraph.graph import StateGraph, END
# ============= DATA EXPORT & VISUALIZATION =============
from visualization_utils import visualize_daily_plan, visualize_graph, save_to_excel, save_log, parse_plan_to_timeline
from loguru import logger

class PlanState(TypedDict):
    """State that flows through the graph"""
    user_profile: str  # Context string
    # planning
    initial_plan: str  # Initial plan generated by the LLM
    planning_attempt_count: int  # How many times we've tried to refine the plan
    # validation
    is_valid: bool
    validation_issues: Annotated[list, operator.add]  # List of issues found during validation
    # feedback loop
    feedback_for_planner: str  # Feedback to improve the plan
    # optimization
    final_plan: str  # The optimized plan after feedback loop
    optimization_notes: str
    # history
    messages: Annotated[list, operator.add]  # Conversation history



def create_planning_agent():
    """Create a simple LangGraph agent with one LLM node using HuggingFace"""
    # Define the planning node
    def planning_node(state: PlanState) -> PlanState:
        """The actual LLM planning logic"""
        # Using HuggingFace Inference API
        client = InferenceClient(token=<your_hf_token_here>)

        # check if its retry with feedback
        attempt = state.get('planning_attempt_count', 0) + 1
        feedback = state.get('feedback_for_planner', '')
        
        logger.info(f"Planning attempt #{attempt}")
        if feedback:
            logger.info(f"Feedback received: {feedback}")

        system_prompt = f"""You are a personal planning assistant. 

        {state['user_profile']}

        Create a realistic, actionable daily plan that:
        1. Fits within their available free time
        2. Helps them achieve their goals
        3. Addresses their struggles
        4. Works around their existing routine

        IMPORTANT: Format your plan with TIMES like this:
        - 18:00 - Exercise (60min)
        - 19:00 - Study LangChain (90min)
        - 20:30 - Review notes (30min)
        
        Keep it practical and not overwhelming
        """
        if feedback:
            system_prompt += f"\n\nPREVIOUS ATTEMPT HAD ISSUES:\n{feedback}\n\nPlease fix these issues in your new plan."
        
        # Use chat_completion for Mistral Instruct models
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Create my daily plan for today"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model="meta-llama/Llama-3.2-3B-Instruct",
            max_tokens=512,
            temperature=0.7,
        )
        
        # Extract the response text
        plan = response.choices[0].message.content
        
        logger.info(f"Generated plan:\n{plan}")
        
        return {
            "initial_plan": plan,
            "planning_attempt_count": attempt,
            "messages": [plan]
        }
    
    # ========== NODE 2: VALIDATOR ==========
    def validator_node(state: PlanState) -> PlanState:
        """Validate the plan for feasibility and goal alignment"""
        plan = state['initial_plan']
        profile_str = state['user_profile']
        
        # Extract free time from profile
        import re
        free_time_match = re.search(r'Available free time:\s*([\d.]+)\s*hours', profile_str)
        free_time_hours = float(free_time_match.group(1)) if free_time_match else 3.0
        
        # Extract goals
        goals_match = re.search(r'Goals:\s*(.+)', profile_str)
        goals = goals_match.group(1).lower() if goals_match else ""
        
        issues = []
        
        # Check 1: Time validation
        time_pattern = r'\((\d+)min\)'
        time_matches = re.findall(time_pattern, plan)
        total_minutes = sum(int(m) for m in time_matches)
        total_hours = total_minutes / 60
        
        if total_hours > free_time_hours + 0.5:  # Allow 30min buffer
            issues.append(f"Plan requires {total_hours:.1f} hours but user only has {free_time_hours} hours free")
        
        # Check 2: Goal alignment
        if goals and not any(keyword in plan.lower() for keyword in goals.split()):
            issues.append(f"Plan doesn't address user's goals: {goals}")
        
        # Check 3: Has actual activities
        if not time_matches or len(time_matches) < 2:
            issues.append("Plan needs more structured activities with time durations")
        
        # Check 4: Time format present
        if not re.search(r'\d{1,2}:\d{2}', plan):
            issues.append("Plan must include specific times (e.g., 18:00 - Activity)")
        
        is_valid = len(issues) == 0
        
        if is_valid:
            logger.success("✓ Plan validation passed")
        else:
            logger.warning(f"✗ Plan validation failed with {len(issues)} issues:")
            for issue in issues:
                logger.warning(f"  - {issue}")
        
        return {
            "is_valid": is_valid,
            "validation_issues": issues,
            "messages": [f"Validator: {'✓ Valid' if is_valid else f'✗ Found {len(issues)} issues'}"]
        }
    
    # ========== NODE 3: FEEDBACK ==========
    def feedback_node(state: PlanState) -> PlanState:
        """Generate constructive feedback for the planner"""
        issues = state.get('validation_issues', [])
        
        feedback = "Please revise the plan to fix these issues:\n"
        for i, issue in enumerate(issues, 1):
            feedback += f"{i}. {issue}\n"
        
        feedback += "\nMake sure to:\n"
        feedback += "- Include specific times (e.g., 18:00 - Activity)\n"
        feedback += "- Add duration for each activity (e.g., 60min)\n"
        feedback += "- Stay within available free time\n"
        feedback += "- Address the user's stated goals\n"
        
        logger.warning(f"Validation failed with {len(issues)} issues. Generating feedback.")
        logger.info(f"Feedback to planner:\n{feedback}")
        
        return {
            "feedback_for_planner": feedback,
            "messages": [f"Feedback: Sending {len(issues)} issues back to planner"]
        }
    

    def optimizer_node(state: PlanState) -> PlanState:
        """ optimize validated plan based on validation feedback """
        client = InferenceClient(token=<your_hf_token_here)

        plan = state['initial_plan']
        profile = state['user_profile']
        system_prompt = f"""You are a planning optimization expert.

        {profile}

        Take this validated plan and optimize it:
        {plan}

        Optimization goals:
        1. Reorder tasks for optimal energy (hard tasks first, easy tasks later)
        2. Group similar activities for flow state
        3. Add 5-10 min breaks between intensive tasks
        4. Consider the user's struggles (procrastination, evening delays)
        5. Keep the same time format and durations

        Return ONLY the optimized plan with the same time format."""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Optimize this plan"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model="meta-llama/Llama-3.2-3B-Instruct",
            max_tokens=512,
            temperature=0.5,
        )
        optimized_plan = response.choices[0].message.content
        
        logger.success("Plan optimization complete")
        logger.info(f"Optimized plan:\\n{optimized_plan}")
        
        return {
            "final_plan": optimized_plan,
            "optimization_notes": "Reordered for energy levels, grouped similar tasks, added breaks",
            "messages": ["Optimizer: Plan optimized for productivity"]
        }

    # ========== ROUTING FUNCTIONS ==========
    def route_after_validation(state: PlanState) -> str:
        """Decide where to go after validation"""
        max_attempts = 2
        
        current_attempt = state.get('planning_attempt_count', 0)
        
        # Too many attempts? Give up and use what we have
        if current_attempt >= max_attempts:
            logger.warning(f"⚠️  Max attempts ({max_attempts}) reached, proceeding with current plan")
            return "optimizer"
        
        # Valid? Move to optimizer
        if state.get('is_valid', False):
            logger.info("Plan is valid, moving to optimizer")
            return "optimizer"
        
        # Invalid? Send feedback and retry
        logger.info(f"Plan is invalid (attempt {current_attempt}/{max_attempts}), sending feedback")
        return "feedback"
    

    ### BUILD THE GRAPH ####
    workflow = StateGraph(PlanState)
    
    # Add single node
    workflow.add_node("planner", planning_node)
    workflow.add_node("validator", validator_node)
    workflow.add_node("feedback", feedback_node)
    workflow.add_node('optimizer', optimizer_node)
    
    # Simple flow: START -> planner -> END
    workflow.set_entry_point("planner")
    workflow.add_edge("planner", "validator")

    #conditional edge after validator
    workflow.add_conditional_edges(
        "validator",
        route_after_validation,
        {
            "feedback": "feedback",
            "optimizer": "optimizer"
        }
    )

    workflow.add_edge("feedback", "planner")  # Loop back to planner after feedback
    workflow.add_edge("optimizer", END)  # End after optimization
    
    return workflow.compile()



def create_dummy_profile() -> UserProfile:
    """Create a dummy profile for testing"""
    profile = UserProfile()
    profile.name = "jedrzej"
    profile.free_time_hours = 3.0
    profile.goals = "learn langchain and langraph"
    profile.struggles = "not working during working hours, waiting till the evening to start sometimes"
    
    # Add a basic routine
    profile.daily_routine = pd.DataFrame([
        {'time': '09:00', 'activity': 'Start work', 'duration_mins': 480},
        {'time': '17:00', 'activity': 'Finish work', 'duration_mins': 60},
        {'time': '18:00', 'activity': 'Free time starts', 'duration_mins': 180},
    ])
    
    return profile
    

def main():
    """Run the planning agent"""
    
    # Step 1: Collect user profile (VOICE BY DEFAULT)
    # collector = ProfileCollector()
    # profile = collector.collect_profile(use_voice=False)  # Set False for text mode
    profile = create_dummy_profile()
    # print(profile.to_context_string())

#     # Step 2: Create and run agent
    print("\n🤖 Creating your daily plan...\n")
    agent = create_planning_agent()
    
    # Initialize state
    initial_state = {
        "user_profile": profile.to_context_string(),
        "initial_plan": "",
        "planning_attempt_count": 0,
        "is_valid": False,
        "validation_issues": [],
        "feedback_for_planner": "",
        "final_plan": "",
        "optimization_notes": "",
        "messages": []
    }


    result = agent.invoke(initial_state)
    
    # Get the final plan from result
    plan_text = result.get('final_plan') or result.get('initial_plan', '')
    logger.success(f"Final plan generated after {result.get('planning_attempt_count', 0)} attempts")

    # Step 4: Parse plan to structured timeline
    timeline_df = parse_plan_to_timeline(plan_text)

    # Step 5: Save to Excel
    log_id = save_to_excel(profile, plan_text, timeline_df)
    
    # # Step 6: Visualize daily plan
    visualize_daily_plan(timeline_df, save_path=f"plan_plots\daily_plan_{log_id}.png")

    # step 7 save plan text to txt file for debug
    save_log(log_id, plan_text)

    # Step 8: Visualize the graph architecture
    visualize_graph(agent)


if __name__ == "__main__":
    main()