import pandas as pd
from typing import TypedDict, Annotated
import operator
from user_profile import UserProfile
from huggingface_hub import InferenceClient
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from datetime import datetime
import os
from dotenv import load_dotenv
# ============= DATA EXPORT & VISUALIZATION =============
from visualization_utils import visualize_daily_plan, visualize_graph, save_to_excel, save_log, parse_plan_to_timeline
from loguru import logger
# Add after existing imports
from dotenv import load_dotenv
from rag_health_agent import get_rag_health_knowledge

# Load environment variables from .env file
load_dotenv()
LLM_MODEL = os.getenv('LLM_MODEL')

class PlanState(TypedDict):
    """State that flows through the graph"""
    user_profile: str  # Context string
    # planning
    initial_plan: str  # Initial plan generated by the LLM
    planning_attempt_count: int  # How many times we've tried to refine the plan
    # validation
    is_valid: bool
    validation_issues: Annotated[list, operator.add]  # List of issues found during validation
    # feedback loop
    feedback_for_planner: str  # Feedback to improve the plan
    # optimization
    final_plan: str  # The optimized plan after feedback loop
    optimization_notes: str
    # multi-agent collaboration
    health_schedule: str  # Health agent output
    productivity_schedule: str  # Productivity agent output
    past_feedback_summary: str  # Historical user feedback from Excel
    coordinator_plan: str  # Final coordinated plan
    # human-in-the-loop
    human_feedback: str  # User's requested changes
    human_approved: bool  # Whether user approved the plan
    refinement_count: int  # How many times user requested changes
    # history
    messages: Annotated[list, operator.add]  # Conversation history


def load_past_feedback(name_id: str, excel_path: str = "planning_data.xlsx") -> str:
    """Load all past human feedback for this user from Excel"""
    if not os.path.exists(excel_path):
        return "No past feedback available (first time user)."
    
    try:
        df = pd.read_excel(excel_path, sheet_name='plan_summary')
        user_plans = df[df['name_id'] == name_id]
        
        if user_plans.empty:
            return "No past feedback available (first time user)."
        
        # Get feedback column (if exists)
        if 'human_feedback' not in user_plans.columns:
            return "No past feedback tracked yet."
        
        feedback_list = user_plans['human_feedback'].dropna()
        feedback_list = [f.strip() for f in feedback_list if f and str(f).strip() and str(f).strip() != '']
        
        if not feedback_list:
            return "No past feedback available (user always approved without changes)."
        
        # Analyze patterns
        summary = f"📊 Past User Feedback Analysis ({len(feedback_list)} instances):\n"
        summary += "="*50 + "\n"
        
        # Show last 5 feedback entries
        for i, fb in enumerate(list(feedback_list)[-5:], 1):
            summary += f"{i}. \"{fb}\"\n"
        
        summary += "\n💡 Detected Patterns:\n"
        
        # Simple pattern detection
        all_feedback = " ".join(feedback_list).lower()
        
        if "exercise" in all_feedback and ("earlier" in all_feedback or "morning" in all_feedback):
            summary += "- User prefers exercise early in the day\n"
        if "break" in all_feedback or "rest" in all_feedback:
            summary += "- User needs frequent breaks\n"
        if "shorter" in all_feedback or "long" in all_feedback:
            summary += "- User prefers shorter work sessions\n"
        if "move" in all_feedback or "change time" in all_feedback:
            summary += "- User often adjusts timing\n"
        
        summary += "="*50
        
        return summary
        
    except Exception as e:
        logger.error(f"Error loading past feedback: {e}")
        return "Error loading past feedback."


def create_planning_agent(checkpoint_path: str = "checkpoints.db"):
    """Create a planning agent with SqliteSaver checkpointing"""
    
    # Create checkpointer
    # checkpointer = SqliteSaver.from_conn_string(checkpoint_path)

    import sqlite3

    # Create connection first
    conn = sqlite3.connect(checkpoint_path, check_same_thread=False)

    # Then create saver from connection
    checkpointer = SqliteSaver(conn)


    logger.info(f"📂 Checkpointer initialized: {checkpoint_path}")
    
    # Define the planning node
    def planning_node(state: PlanState) -> PlanState:
        """The actual LLM planning logic"""
        # Using HuggingFace Inference API
        client = InferenceClient(token=os.getenv('HUGGINGFACEHUB_API_TOKEN'))

        # check if its retry with feedback
        attempt = state.get('planning_attempt_count', 0) + 1
        feedback = state.get('feedback_for_planner', '')
        
        logger.info(f"Planning attempt #{attempt}")
        if feedback:
            logger.info(f"Feedback received: {feedback}")

        system_prompt = f"""You are a personal planning assistant. 

        {state['user_profile']}

        Create a realistic, actionable daily plan that:
        1. Fits within their available free time
        2. Helps them achieve their goals
        3. Addresses their struggles
        4. Works around their existing routine

        IMPORTANT: Format your plan with TIMES like this:
        - 18:00 - Exercise (60min)
        - 19:00 - Study LangChain (90min)
        - 20:30 - Review notes (30min)
        
        Keep it practical and not overwhelming
        """
        if feedback:
            system_prompt += f"\n\nPREVIOUS ATTEMPT HAD ISSUES:\n{feedback}\n\nPlease fix these issues in your new plan."
        
        # Use chat_completion for Mistral Instruct models
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Create my daily plan for today"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model=LLM_MODEL,
            max_tokens=512,
            temperature=0.7,
        )
        
        # Extract the response text
        plan = response.choices[0].message.content
        
        logger.info(f"Generated plan:\n{plan}")
        
        return {
            "initial_plan": plan,
            "planning_attempt_count": attempt,
            "messages": [plan]
        }
    
    # ========== NODE 2: VALIDATOR ==========
    def validator_node(state: PlanState) -> PlanState:
        """Validate the plan for feasibility and goal alignment"""
        plan = state['initial_plan']
        profile_str = state['user_profile']
        
        # Extract free time from profile
        import re
        free_time_match = re.search(r'Available free time:\s*([\d.]+)\s*hours', profile_str)
        free_time_hours = float(free_time_match.group(1)) if free_time_match else 3.0
        
        # Extract goals
        goals_match = re.search(r'Goals:\s*(.+)', profile_str)
        goals = goals_match.group(1).lower() if goals_match else ""
        
        issues = []
        
        # Check 1: Time validation
        time_pattern = r'\((\d+)min\)'
        time_matches = re.findall(time_pattern, plan)
        total_minutes = sum(int(m) for m in time_matches)
        total_hours = total_minutes / 60
        
        if total_hours > free_time_hours + 0.5:  # Allow 30min buffer
            issues.append(f"Plan requires {total_hours:.1f} hours but user only has {free_time_hours} hours free")
        
        # Check 2: Goal alignment
        if goals and not any(keyword in plan.lower() for keyword in goals.split()):
            issues.append(f"Plan doesn't address user's goals: {goals}")
        
        # Check 3: Has actual activities
        if not time_matches or len(time_matches) < 2:
            issues.append("Plan needs more structured activities with time durations")
        
        # Check 4: Time format present
        if not re.search(r'\d{1,2}:\d{2}', plan):
            issues.append("Plan must include specific times (e.g., 18:00 - Activity)")
        
        is_valid = len(issues) == 0
        
        if is_valid:
            logger.success("✓ Plan validation passed")
        else:
            logger.warning(f"✗ Plan validation failed with {len(issues)} issues:")
            for issue in issues:
                logger.warning(f"  - {issue}")
        
        return {
            "is_valid": is_valid,
            "validation_issues": issues,
            "messages": [f"Validator: {'✓ Valid' if is_valid else f'✗ Found {len(issues)} issues'}"]
        }
    
    # ========== NODE 3: FEEDBACK ==========
    def feedback_node(state: PlanState) -> PlanState:
        """Generate constructive feedback for the planner"""
        issues = state.get('validation_issues', [])
        
        feedback = "Please revise the plan to fix these issues:\n"
        for i, issue in enumerate(issues, 1):
            feedback += f"{i}. {issue}\n"
        
        feedback += "\nMake sure to:\n"
        feedback += "- Include specific times (e.g., 18:00 - Activity)\n"
        feedback += "- Add duration for each activity (e.g., 60min)\n"
        feedback += "- Stay within available free time\n"
        feedback += "- Address the user's stated goals\n"
        
        logger.warning(f"Validation failed with {len(issues)} issues. Generating feedback.")
        logger.info(f"Feedback to planner:\n{feedback}")
        
        return {
            "feedback_for_planner": feedback,
            "messages": [f"Feedback: Sending {len(issues)} issues back to planner"]
        }
    

    def optimizer_node(state: PlanState) -> PlanState:
        """ optimize validated plan based on validation feedback """
        client = InferenceClient(token=os.getenv('HUGGINGFACEHUB_API_TOKEN'))

        plan = state['initial_plan']
        profile = state['user_profile']
        system_prompt = f"""You are a planning optimization expert.

        {profile}

        Take this validated plan and optimize it:
        {plan}

        Optimization goals:
        1. Reorder tasks for optimal energy (hard tasks first, easy tasks later)
        2. Group similar activities for flow state
        3. Add 5-10 min breaks between intensive tasks
        4. Consider the user's struggles (procrastination, evening delays)
        5. Keep the same time format and durations

        Return ONLY the optimized plan with the same time format."""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Optimize this plan"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model=LLM_MODEL,
            max_tokens=512,
            temperature=0.5,
        )
        optimized_plan = response.choices[0].message.content
        
        logger.success("Plan optimization complete")
        logger.info(f"Optimized plan:\n{optimized_plan}")
        
        return {
            "final_plan": optimized_plan,
            "optimization_notes": "Reordered for energy levels, grouped similar tasks, added breaks",
            "messages": ["Optimizer: Plan optimized for productivity"]
        }
    
    # ========== NODE 5: HUMAN REVIEW (INTERRUPT) ==========
    def human_review_node(state: PlanState) -> PlanState:
        """Show plan to human and wait for approval or feedback"""
        plan = state.get('final_plan', '')
        refinement_count = state.get('refinement_count', 0)
        
        logger.info("\n" + "="*60)
        logger.info("👤 HUMAN REVIEW - Your Daily Plan:")
        logger.info("="*60)
        print(plan)
        logger.info("="*60)
        
        if refinement_count > 0:
            logger.info(f"(Refinement attempt #{refinement_count})")
        
        # Ask for approval
        print("\nWhat would you like to do?")
        print("1. ✅ Approve (accept plan as-is)")
        print("2. ✏️  Request changes (provide feedback)")
        print()
        
        choice = input("Your choice (1 or 2): ").strip()
        
        if choice == "1":
            logger.success("✅ Plan approved by user!")
            return {
                "human_approved": True,
                "human_feedback": "",
                "messages": ["Human: Plan approved!"]
            }
        else:
            feedback = input("\n💬 What changes would you like? (be specific): ").strip()
            logger.info(f"📝 User feedback: {feedback}")
            state['human_feedback'] = feedback
            return {
                "human_approved": False,
                "human_feedback": feedback,
                "refinement_count": refinement_count + 1,
                "messages": [f"Human: Requested changes - {feedback}"]
            }
    # ========== NODE 6: REFINEMENT ==========
    def refinement_node(state: PlanState) -> PlanState:
        """Refine plan based on human feedback"""
        client = InferenceClient(token=os.getenv('HUGGINGFACEHUB_API_TOKEN'))
        
        current_plan = state['final_plan']
        human_feedback = state['human_feedback']
        profile = state['user_profile']
        
        logger.info(f"🔧 Refining plan based on feedback: {human_feedback}")
        
        system_prompt = f"""You are a personal planning assistant.

        {profile}

        Current plan:
        {current_plan}

        The user reviewed the plan and requested these changes:
        "{human_feedback}"

        Create a revised plan that:
        1. Addresses the user's specific feedback
        2. Maintains the same time format and structure
        3. Keeps what was working well
        4. Makes ONLY the changes requested

        Return ONLY the revised plan."""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Revise the plan: {human_feedback}"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model=LLM_MODEL,
            max_tokens=512,
            temperature=0.7,
        )
        
        revised_plan = response.choices[0].message.content
        
        logger.success("Plan refined based on user feedback")
        logger.info(f"Revised plan:\n{revised_plan}")
        
        return {
            "final_plan": revised_plan,
            "messages": ["Refinement: Plan updated based on human feedback"]
        }
    
    # ========== NODE 7: HEALTH AGENT ==========

    def health_agent_node(state: PlanState) -> PlanState:
        """Specialized agent for health and wellness scheduling (with optional RAG)"""
        client = InferenceClient(token=os.getenv('HUGGINGFACEHUB_API_TOKEN'), provider="together")
        
        profile = state['user_profile']
        base_plan = state['final_plan']
        
        # Check if RAG is enabled
        use_rag = os.getenv('USE_RAG_HEALTH_AGENT', 'false').lower() == 'true'
        
        if use_rag:
            logger.info("🏃 Health Agent (RAG-ENABLED): Creating evidence-based health schedule...")
            
            # Get RAG knowledge base
            rag_kb = get_rag_health_knowledge()
            
            if rag_kb:
                # Create query from user context
                query = f"""Exercise timing and energy management for someone who:
                - Has {profile.split('free time:')[1].split('hours')[0].strip()} hours free time
                - Struggles with: procrastination and evening delays
                - Goals: learn new skills effectively
                
                What does research say about optimal exercise timing, break placement, and energy management?"""
                
                # Retrieve relevant knowledge
                rag_context = rag_kb.get_context(query, k=3)
                logger.info(f"📚 Retrieved RAG context ({len(rag_context)} chars)")
            else:
                logger.warning("⚠️ RAG knowledge base not available, falling back to simple mode")
                rag_context = ""
                use_rag = False
        
        # Build system prompt (with or without RAG context)
        if use_rag and rag_context:
            system_prompt = f"""You are a health and wellness expert with access to research-based knowledge.

    {rag_context}

    USER PROFILE:
    {profile}

    CURRENT PLAN:
    {base_plan}

    Based on the RESEARCH EVIDENCE above and the user's profile:
    1. Suggest optimal exercise timing (60min)
    2. Add strategic breaks between intensive tasks
    3. Apply energy management principles from the research
    4. Consider the user's struggles with procrastination

    Create health recommendations that FIT WITHIN the existing time blocks.
    Enhance the plan with exercise and breaks based on EVIDENCE.

    Return ONLY the enhanced plan with health additions.
    Keep the same time format (HH:MM - Activity (XXmin)).
    CITE which research principles you're applying (e.g., "Based on energy management research...")"""
        else:
            logger.info("🏃 Health Agent (SIMPLE MODE): Creating health-focused schedule...")
            
            system_prompt = f"""You are a health and wellness expert specializing in exercise timing and energy management.

    {profile}

    Current optimized plan:
    {base_plan}

    Based on the user's struggles and goals:
    1. Suggest optimal exercise timing (60min)
    2. Add strategic breaks between intensive tasks
    3. Consider energy patterns (user procrastinates in evening, so exercise early might help)
    4. Ensure recovery time

    Create health recommendations that FIT WITHIN the existing time blocks.
    Enhance the plan with exercise and breaks.

    Return ONLY the enhanced plan with health additions.
    Keep the same time format (HH:MM - Activity (XXmin))."""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Enhance this plan with health and wellness schedule"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model="meta-llama/Llama-3.3-70B-Instruct",
            max_tokens=512,
            temperature=0.7,
        )
        
        health_enhanced = response.choices[0].message.content
        
        mode = "RAG-enabled (evidence-based)" if use_rag else "Simple LLM-based"
        logger.success(f"✅ Health agent ({mode}): Exercise and break schedule added")
        logger.info(f"Health-enhanced plan:\n{health_enhanced}")
        
        return {
            "health_schedule": health_enhanced,
            "messages": [f"Health Agent ({mode}): Added exercise timing and breaks"]
        }
    
    # ========== NODE 8: PRODUCTIVITY AGENT ==========
    def productivity_agent_node(state: PlanState) -> PlanState:
        """Specialized agent for productivity optimization"""
        client = InferenceClient(token=os.getenv('HUGGINGFACEHUB_API_TOKEN'))
        
        profile = state['user_profile']
        health_plan = state['health_schedule']
        
        logger.info("💼 Productivity Agent: Adding productivity strategies...")
        
        system_prompt = f"""You are a productivity expert specializing in combating procrastination and time management.

{profile}

Current plan (with health schedule):
{health_plan}

The user struggles with:
- Not working during working hours
- Waiting till evening to start tasks
- Procrastination

Apply productivity techniques:
1. Implementation intentions (specific triggers for starting)
2. Time-blocking for deep work
3. "Eat the frog" principle (hard tasks first when energy is high)
4. Small wins to build momentum
5. Pomodoro-style work sessions

Enhance the plan with productivity strategies.
Add specific cues like "After exercise, immediately start..."

Return ONLY the productivity-enhanced plan.
Keep the same time format."""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Add productivity techniques to this plan"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model=LLM_MODEL,
            max_tokens=512,
            temperature=0.7,
        )
        
        productivity_enhanced = response.choices[0].message.content
        
        logger.success("✅ Productivity agent: Strategies and techniques added")
        logger.info(f"Productivity-enhanced plan:\n{productivity_enhanced}")
        
        return {
            "productivity_schedule": productivity_enhanced,
            "messages": ["Productivity Agent: Added anti-procrastination techniques"]
        }
    
    # ========== NODE 9: COORDINATOR AGENT (THE SMART ONE) ==========
    def coordinator_agent_node(state: PlanState) -> PlanState:
        """Coordinator that merges specialist outputs and learns from past feedback"""
        client = InferenceClient(token=os.getenv('HUGGINGFACEHUB_API_TOKEN'))
        
        profile = state['user_profile']
        health_output = state['health_schedule']
        productivity_output = state['productivity_schedule']
        past_feedback = state.get('past_feedback_summary', 'No past feedback available.')
        
        logger.info("🎯 Coordinator Agent: Merging outputs and applying learned patterns...")
        logger.info(f"\n{past_feedback}\n")
        
        system_prompt = f"""You are a master coordinator who combines expert advice and learns from user preferences.

        {profile}

        HEALTH AGENT RECOMMENDATIONS:
        {health_output}

        PRODUCTIVITY AGENT RECOMMENDATIONS:
        {productivity_output}

        {past_feedback}

        Your job:
        1. Merge health and productivity suggestions into ONE cohesive plan
        2. Resolve time conflicts based on user goals
        3. Apply lessons learned from past feedback
        4. Ensure the plan fits within available free time
        5. Produce a realistic daily plan

        IMPORTANT SCHEDULING RULES:
        - Use time blocks as headings (07:00-08:30, 09:00-10.30 etc.)
        - Do NOT include durations.
        - Each task should contain ONE short description sentence.
        - Times should appear ONLY as section headings.
        - Never mention time inside the task description.

        OUTPUT FORMAT (STRICT):

        Daily Plan Overview:
        Write 1–2 sentences summarizing the day and why it was chosen.

        Schedule:

        07:00 - 07:30
        Task title - One short sentence describing what to do.

        07:30 - 09:00
        Task title - One short sentence describing what to do.

        09:00 - 10:30
        Task title - One short sentence describing what to do.

        Continue for all planned hours.

        Return ONLY the final coordinated plan following this exact format.
        """

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": "Create the final coordinated plan"}
        ]
        
        response = client.chat_completion(
            messages=messages,
            model=LLM_MODEL,
            max_tokens=512,
            temperature=0.6,
        )
        
        final_coordinated = response.choices[0].message.content
        
        logger.success("✅ Coordinator: Final plan created with learned preferences")
        logger.info(f"Coordinated plan:\n{final_coordinated}")
        
        return {
            "coordinator_plan": final_coordinated,
            "final_plan": final_coordinated,  # Update final_plan for human review
            "messages": ["Coordinator: Merged all inputs and applied historical learnings"]
        }

    # ========== ROUTING FUNCTIONS ==========
    def route_after_validation(state: PlanState) -> str:
        """Decide where to go after validation"""
        max_attempts = 2

        current_attempt = state.get('planning_attempt_count', 0)

        # Too many attempts? Give up and use what we have
        if current_attempt >= max_attempts:
            logger.warning(f"⚠️  Max attempts ({max_attempts}) reached, proceeding with current plan")
            return "optimizer"
        
        # Valid? Move to optimizer
        if state.get('is_valid', False):
            logger.info("Plan is valid, moving to optimizer")
            return "optimizer"
        
        # Invalid? Send feedback and retry
        logger.info(f"Plan is invalid (attempt {current_attempt}/{max_attempts}), sending feedback")
        return "feedback"
    
    def route_after_human_review(state: PlanState) -> str:
        """Decide where to go after human review"""
        if state.get('human_approved', False):
            logger.success("✅ Human approved - ending workflow")
            return "end"
        else:
            logger.info("🔄 Human requested changes - going to refinement")
            return "refinement"
    

    ### BUILD THE GRAPH ####
    workflow = StateGraph(PlanState)
    
    # Add nodes
    workflow.add_node("planner", planning_node)
    workflow.add_node("validator", validator_node)
    workflow.add_node("feedback", feedback_node)
    workflow.add_node('optimizer', optimizer_node)
    workflow.add_node("health_agent", health_agent_node)
    workflow.add_node("productivity_agent", productivity_agent_node)
    workflow.add_node("coordinator", coordinator_agent_node)
    workflow.add_node("human_review", human_review_node)
    workflow.add_node("refinement", refinement_node)
    
    # Define edges
    workflow.set_entry_point("planner")
    workflow.add_edge("planner", "validator")

    # Conditional edge after validator
    workflow.add_conditional_edges(
        "validator",
        route_after_validation,
        {
            "feedback": "feedback",
            "optimizer": "optimizer"
        }
    )

    workflow.add_edge("feedback", "planner")  # Loop back to planner after feedback
    
    # Multi-agent pipeline (sequential)
    workflow.add_edge("optimizer", "health_agent")
    workflow.add_edge("health_agent", "productivity_agent")
    workflow.add_edge("productivity_agent", "coordinator")
    workflow.add_edge("coordinator", "human_review")  # Coordinator goes to human review
    
    # Conditional edge after human review
    workflow.add_conditional_edges(
        "human_review",
        route_after_human_review,
        {
            "end": END,
            "refinement": "refinement"
        }
    )
    
    # Refinement loops back to human review
    workflow.add_edge("refinement", "human_review")
    
    # Compile with checkpointer
    return workflow.compile(checkpointer=checkpointer)


# ========== CHECKPOINT UTILITIES ==========

def view_checkpoint_history(agent, config):
    """View all checkpoints for a thread"""
    logger.info(f"\n{'='*50}")
    logger.info(f"📜 CHECKPOINT HISTORY")
    logger.info(f"{'='*50}")
    
    try:
        history = list(agent.get_state_history(config))
    except Exception as e:
        logger.error(f"Error getting checkpoint history: {e}")
        return
    
    for i, state_snapshot in enumerate(reversed(history)):
        logger.info(f"\nCheckpoint #{i+1}:")
        logger.info(f"  Next node: {state_snapshot.next}")
        logger.info(f"  Attempt: {state_snapshot.values.get('planning_attempt_count', 0)}")
        logger.info(f"  Valid: {state_snapshot.values.get('is_valid', 'N/A')}")
        
        if state_snapshot.values.get('validation_issues'):
            logger.info(f"  Issues: {len(state_snapshot.values['validation_issues'])}")
    
    logger.info(f"\n{'='*50}\n")


def resume_from_checkpoint(agent, config):
    """Resume execution from last checkpoint"""
    logger.info("🔄 Resuming from last checkpoint...")
    
    # Get current state
    current_state = agent.get_state(config)
    logger.info(f"Last node: {current_state.next}")
    logger.info(f"Current state keys: {list(current_state.values.keys())}")
    
    # Resume execution
    result = agent.invoke(None, config)
    return result


def create_dummy_profile() -> UserProfile:
    """Create a dummy profile for testing"""
    profile = UserProfile()
    profile.name = "jedrzej"
    profile.free_time_hours = 3.0
    profile.goals = "learn langchain and langraph"
    profile.struggles = "not working during working hours, waiting till the evening to start sometimes"
    
    # Add a basic routine
    profile.daily_routine = pd.DataFrame([
        {'time': '09:00', 'activity': 'Start work', 'duration_mins': 480},
        {'time': '17:00', 'activity': 'Finish work', 'duration_mins': 60},
        {'time': '18:00', 'activity': 'Free time starts', 'duration_mins': 180},
    ])
    
    return profile
    

def main():
    """Run the planning agent with multi-agent collaboration"""
    
    # Step 1: Create profile
    profile = create_dummy_profile()
    name_id = f"user_{profile.name.lower().replace(' ', '_')}"
    
    # Step 2: Load past feedback for this user
    logger.info("\n📚 Loading past user feedback...")
    past_feedback = load_past_feedback(name_id, excel_path="planning_data.xlsx")
    logger.info(f"\n{past_feedback}\n")
    
    # Step 3: Create agent with checkpointing
    logger.info("\n🤖 Creating your daily plan with multi-agent collaboration...\n")
    agent = create_planning_agent(checkpoint_path="planning_checkpoints.db")
    
    # Step 4: Create thread config (unique per user session)
    thread_id = f"user_{profile.name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    config = {
        "configurable": {
            "thread_id": thread_id
        }
    }
    logger.info(f"🧵 Thread ID: {thread_id}")
    
    # Step 5: Initialize state with multi-agent fields
    initial_state = {
        "user_profile": profile.to_context_string(),
        "initial_plan": "",
        "planning_attempt_count": 0,
        "is_valid": False,
        "validation_issues": [],
        "feedback_for_planner": "",
        "final_plan": "",
        "optimization_notes": "",
        "health_schedule": "",
        "productivity_schedule": "",
        "past_feedback_summary": past_feedback,
        "coordinator_plan": "",
        "human_feedback": "",
        "human_approved": False,
        "refinement_count": 0,
        "messages": []
    }

    # Step 6: Run agent (multi-agent collaboration + human-in-the-loop!)
    result = agent.invoke(initial_state, config)
    
    # Step 7: View checkpoint history
    view_checkpoint_history(agent, config)
    
    # Step 8: Get final plan and human feedback
    plan_text = result.get('final_plan') or result.get('initial_plan', '')
    human_feedback_text = result.get('human_feedback', '')
    
    logger.success(f"\n🎉 Final plan approved after {result.get('refinement_count', 0)} refinements!")
    logger.info(f"Planning attempts: {result.get('planning_attempt_count', 0)}")

    # Step 9: Parse plan to structured timeline
    timeline_df = parse_plan_to_timeline(plan_text)

    # Step 10: Save to Excel WITH human feedback
    log_id = save_to_excel(
        profile, 
        plan_text, 
        timeline_df, 
        excel_path="planning_data.xlsx",
        thread_id=thread_id,
        human_feedback=human_feedback_text,
        # refinement_count=result.get('refinement_count', 0)
    )
    
    # Step 11: Visualize daily plan
    visualize_daily_plan(timeline_df, save_path=f"plan_plots/daily_plan_{log_id}.png")

    # Step 12: Save plan text to txt file for debug
    save_log(log_id, plan_text)

    # Step 13: Visualize the graph architecture
    visualize_graph(agent)
    
    logger.info(f"\n✅ Session complete! Thread ID: {thread_id}")
    logger.info(f"💾 Checkpoints saved to: planning_checkpoints.db")
    logger.info(f"💾 Plan and feedback saved to: planning_data.xlsx")


if __name__ == "__main__":
    print('taki jest token:', os.getenv('HUGGINGFACEHUB_API_TOKEN'))
    main()